- name: "Playing with Ansible"
  hosts: localhost
  connection: local 
  become: True
  tasks:
    - name: Install packages
      npm:
        name: "nodemon"
        state: "present"
        path: /Volumes/data/dev/www/
    - name: Deploy static website
      copy:
        src: dist
        dest: /Volumes/data/dev/www/
